# Generated by Django 5.2.1 on 2025-06-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.TextField(blank=True),
        ),
    ]
