# Generated by Django 5.2.1 on 2025-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_userprofile_balance_userprofile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
