# Generated by Django 5.2.1 on 2025-06-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_userprofile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
